# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20171208_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body_content', models.TextField(max_length=250)),
                ('url', models.URLField()),
                ('tag', models.ManyToManyField(to='qa.tag')),
            ],
        ),
    ]
